import { Agent, DomainPack, Tool, AgentRun, ActivityItem, DashboardMetrics } from '@/types';

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'HR Assistant',
    description: 'Handles employee inquiries and HR documentation',
    avatar: '/agents/hr.png',
    domainPackId: 'hr-crm',
    tenantId: 'tenant-1',
    status: 'running',
    configuration: {
      model: 'claude-3-sonnet',
      temperature: 0.7,
      maxTokens: 4096,
      systemPrompt: 'You are an HR assistant...',
      tools: ['slack', 'notion', 'email'],
      memory: 'long-term',
      autonomyLevel: 'semi-autonomous',
    },
    metrics: {
      totalRuns: 1247,
      successRate: 98.5,
      avgExecutionTime: 2340,
      lastRunAt: new Date(Date.now() - 300000),
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Data Analyst',
    description: 'Analyzes business metrics and generates reports',
    avatar: '/agents/analyst.png',
    domainPackId: null,
    tenantId: 'tenant-1',
    status: 'idle',
    configuration: {
      model: 'claude-3-opus',
      temperature: 0.3,
      maxTokens: 8192,
      systemPrompt: 'You are a data analyst...',
      tools: ['database', 'sheets', 'charts'],
      memory: 'short-term',
      autonomyLevel: 'supervised',
    },
    metrics: {
      totalRuns: 892,
      successRate: 99.2,
      avgExecutionTime: 5670,
      lastRunAt: new Date(Date.now() - 3600000),
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Customer Support',
    description: 'Handles customer tickets and support queries',
    avatar: '/agents/support.png',
    domainPackId: 'hr-crm',
    tenantId: 'tenant-1',
    status: 'running',
    configuration: {
      model: 'claude-3-sonnet',
      temperature: 0.5,
      maxTokens: 4096,
      systemPrompt: 'You are a customer support agent...',
      tools: ['zendesk', 'slack', 'knowledge-base'],
      memory: 'long-term',
      autonomyLevel: 'autonomous',
    },
    metrics: {
      totalRuns: 3421,
      successRate: 97.8,
      avgExecutionTime: 1890,
      lastRunAt: new Date(Date.now() - 60000),
    },
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Research Assistant',
    description: 'Conducts research and summarizes findings',
    avatar: '/agents/research.png',
    domainPackId: 'life-sciences',
    tenantId: 'tenant-1',
    status: 'paused',
    configuration: {
      model: 'claude-3-opus',
      temperature: 0.4,
      maxTokens: 16384,
      systemPrompt: 'You are a research assistant...',
      tools: ['pubmed', 'arxiv', 'notion'],
      memory: 'long-term',
      autonomyLevel: 'supervised',
    },
    metrics: {
      totalRuns: 156,
      successRate: 95.5,
      avgExecutionTime: 12400,
      lastRunAt: new Date(Date.now() - 86400000),
    },
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Code Reviewer',
    description: 'Reviews pull requests and suggests improvements',
    avatar: '/agents/code.png',
    domainPackId: null,
    tenantId: 'tenant-1',
    status: 'error',
    configuration: {
      model: 'claude-3-sonnet',
      temperature: 0.2,
      maxTokens: 8192,
      systemPrompt: 'You are a code reviewer...',
      tools: ['github', 'jira'],
      memory: 'short-term',
      autonomyLevel: 'semi-autonomous',
    },
    metrics: {
      totalRuns: 534,
      successRate: 94.2,
      avgExecutionTime: 4560,
      lastRunAt: new Date(Date.now() - 7200000),
    },
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Meeting Scheduler',
    description: 'Coordinates meetings and manages calendars',
    avatar: '/agents/calendar.png',
    domainPackId: 'hr-crm',
    tenantId: 'tenant-1',
    status: 'running',
    configuration: {
      model: 'claude-3-haiku',
      temperature: 0.3,
      maxTokens: 2048,
      systemPrompt: 'You are a meeting scheduler...',
      tools: ['calendar', 'slack', 'zoom'],
      memory: 'short-term',
      autonomyLevel: 'autonomous',
    },
    metrics: {
      totalRuns: 2156,
      successRate: 99.5,
      avgExecutionTime: 890,
      lastRunAt: new Date(Date.now() - 120000),
    },
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date(),
  },
];

export const mockDomainPacks: DomainPack[] = [
  {
    id: 'hr-crm',
    name: 'HR & CRM Suite',
    slug: 'hr-crm',
    description: 'Complete HR management and CRM automation agents',
    icon: 'Users',
    category: 'hr-crm',
    agentCount: 8,
    version: '2.1.0',
    status: 'active',
  },
  {
    id: 'healthcare',
    name: 'Healthcare Operations',
    slug: 'healthcare',
    description: 'HIPAA-compliant healthcare workflow automation',
    icon: 'Heart',
    category: 'healthcare',
    agentCount: 12,
    version: '1.5.0',
    status: 'active',
  },
  {
    id: 'life-sciences',
    name: 'Life Sciences Research',
    slug: 'life-sciences',
    description: 'Research automation and data analysis for life sciences',
    icon: 'Flask',
    category: 'life-sciences',
    agentCount: 6,
    version: '1.2.0',
    status: 'beta',
  },
  {
    id: 'finance',
    name: 'Financial Services',
    slug: 'finance',
    description: 'Compliance, reporting, and financial analysis agents',
    icon: 'DollarSign',
    category: 'finance',
    agentCount: 10,
    version: '2.0.0',
    status: 'active',
  },
];

export const mockTools: Tool[] = [
  { id: '1', name: 'Slack', slug: 'slack', description: 'Team communication', icon: 'MessageSquare', category: 'communication', provider: 'Slack', status: 'active', isConnected: true },
  { id: '2', name: 'Notion', slug: 'notion', description: 'Documentation and wikis', icon: 'FileText', category: 'data', provider: 'Notion', status: 'active', isConnected: true },
  { id: '3', name: 'GitHub', slug: 'github', description: 'Code repository', icon: 'Github', category: 'integration', provider: 'GitHub', status: 'active', isConnected: true },
  { id: '4', name: 'PostgreSQL', slug: 'postgresql', description: 'Database queries', icon: 'Database', category: 'data', provider: 'PostgreSQL', status: 'active', isConnected: false },
  { id: '5', name: 'Zendesk', slug: 'zendesk', description: 'Customer support', icon: 'Headphones', category: 'communication', provider: 'Zendesk', status: 'active', isConnected: true },
  { id: '6', name: 'Google Sheets', slug: 'sheets', description: 'Spreadsheet data', icon: 'Table', category: 'data', provider: 'Google', status: 'active', isConnected: true },
];

export const mockRecentRuns: AgentRun[] = [
  { id: '1', agentId: '3', agentName: 'Customer Support', status: 'completed', trigger: 'webhook', duration: 1890, tokensUsed: 2340, createdAt: new Date(Date.now() - 60000) },
  { id: '2', agentId: '1', agentName: 'HR Assistant', status: 'completed', trigger: 'manual', duration: 2340, tokensUsed: 1560, createdAt: new Date(Date.now() - 300000) },
  { id: '3', agentId: '6', agentName: 'Meeting Scheduler', status: 'running', trigger: 'scheduled', duration: null, tokensUsed: 890, createdAt: new Date(Date.now() - 120000) },
  { id: '4', agentId: '5', agentName: 'Code Reviewer', status: 'failed', trigger: 'webhook', duration: 4560, tokensUsed: 3200, createdAt: new Date(Date.now() - 7200000) },
  { id: '5', agentId: '2', agentName: 'Data Analyst', status: 'completed', trigger: 'scheduled', duration: 5670, tokensUsed: 4500, createdAt: new Date(Date.now() - 3600000) },
];

export const mockActivity: ActivityItem[] = [
  { id: '1', type: 'run_completed', message: 'Customer Support completed ticket #4521', timestamp: new Date(Date.now() - 60000), agentId: '3', agentName: 'Customer Support' },
  { id: '2', type: 'run_started', message: 'Meeting Scheduler started calendar sync', timestamp: new Date(Date.now() - 120000), agentId: '6', agentName: 'Meeting Scheduler' },
  { id: '3', type: 'run_completed', message: 'HR Assistant processed leave request', timestamp: new Date(Date.now() - 300000), agentId: '1', agentName: 'HR Assistant' },
  { id: '4', type: 'run_failed', message: 'Code Reviewer failed: API rate limit', timestamp: new Date(Date.now() - 7200000), agentId: '5', agentName: 'Code Reviewer' },
  { id: '5', type: 'tool_connected', message: 'Google Sheets integration connected', timestamp: new Date(Date.now() - 86400000) },
  { id: '6', type: 'agent_created', message: 'New agent "Research Assistant" created', timestamp: new Date(Date.now() - 172800000), agentId: '4', agentName: 'Research Assistant' },
];

export const mockDashboardMetrics: DashboardMetrics = {
  activeAgents: 12,
  runsToday: 247,
  successRate: 98.2,
  avgExecutionTime: 3200,
  activeAgentsTrend: 2,
  runsTodayTrend: 15,
  successRateTrend: 0.5,
  avgExecutionTimeTrend: -8,
};
